max_width = 120
tab_spaces = 4
hard_tabs = false

format_strings = true
use_field_init_shorthand = true
wrap_comments = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

edition = "2021"
